# .streamlit/secrets.toml 

[snowflake] 

user = "michaelnguyen" 

password = "Mnguyen26" 

account = "xxx" 

warehouse = "COMPUTE_WH" 

database = "PETS" 

schema = "PUBLIC" 

role = “ACCOUNTADMIN” 
